name: GitHub Pages Upload
on: 
  push:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  Create-Github-Pages-PR:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
