name: GitHub Pages Upload
on: 
  push:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  Create-Github-Pages-PR:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: gh repo list
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create PR
        run: |
          gh pr create \
            --head gh-pages \
            --base main \
            --title "Github Pagesへの自動PR作成" \
            --body ""
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
